"""empty message

Revision ID: 1a92384b43a8
Revises: 
Create Date: 2017-12-03 10:22:32.555484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a92384b43a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('Mid', sa.Integer(), nullable=False),
    sa.Column('MnameCH', sa.String(length=64), nullable=True),
    sa.Column('MnameEN', sa.String(length=64), nullable=True),
    sa.Column('Mgrade', sa.String(length=16), nullable=True),
    sa.Column('Marea', sa.String(length=64), nullable=True),
    sa.Column('Mdate', sa.String(length=16), nullable=True),
    sa.Column('Mtime', sa.String(length=16), nullable=True),
    sa.Column('Mbrief', sa.Text(), nullable=True),
    sa.Column('Mpicture', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Mid'),
    sa.UniqueConstraint('MnameCH'),
    sa.UniqueConstraint('MnameEN'),
    sa.UniqueConstraint('Mpicture')
    )
    op.create_table('am',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.Aid'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.Mid'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    op.create_table('dm',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.Did'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.Mid'], ),
    sa.PrimaryKeyConstraint('director_id', 'movie_id')
    )
    op.create_table('tm',
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.Mid'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.Tid'], ),
    sa.PrimaryKeyConstraint('type_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tm')
    op.drop_table('dm')
    op.drop_table('am')
    op.drop_table('movie')
    # ### end Alembic commands ###
