"""empty message

Revision ID: 7e68f867f7e5
Revises: b9c8b2390473
Create Date: 2017-12-06 14:00:15.372129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e68f867f7e5'
down_revision = 'b9c8b2390473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('Aid', sa.Integer(), nullable=False),
    sa.Column('AnameCH', sa.String(length=64), nullable=True),
    sa.Column('AnameEN', sa.String(length=64), nullable=True),
    sa.Column('Asex', sa.String(length=64), nullable=True),
    sa.Column('Acome_from', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Aid'),
    sa.UniqueConstraint('AnameCH'),
    sa.UniqueConstraint('AnameEN')
    )
    op.create_table('director',
    sa.Column('Did', sa.Integer(), nullable=False),
    sa.Column('DnameCH', sa.String(length=64), nullable=True),
    sa.Column('DnameEN', sa.String(length=64), nullable=True),
    sa.Column('Dsex', sa.String(length=64), nullable=True),
    sa.Column('Dcome_from', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('Did'),
    sa.UniqueConstraint('DnameCH'),
    sa.UniqueConstraint('DnameEN')
    )
    op.create_table('am',
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.Aid'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.Mid'], ),
    sa.PrimaryKeyConstraint('actor_id', 'movie_id')
    )
    op.create_table('dm',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.Did'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.Mid'], ),
    sa.PrimaryKeyConstraint('director_id', 'movie_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dm')
    op.drop_table('am')
    op.drop_table('director')
    op.drop_table('actor')
    # ### end Alembic commands ###
